### ISSUE TITLE
Behat test suite only passes on first run

### ISSUE THREAD

**Issue by grasmash** [acquia/lightning#108]
I believe that this is due to the fact the test suite does not perform any cleanup of created content, which could be done in @afterSuite or would be done automatically if the nodes were created programatically via the Drupal extension.

**Comment by balsama** [comment]
There were three tests that didn't pass after the first run. The first is for landing pages. That method of creating landing pages will go away in beta3 along with that test. So I'm not going to rewrite it (see https://www.drupal.org/node/2666320).

I've rewritten the other two such that behat will automatically clean up the content. I've also written a step definition to clean up the associated URL definitions since Drupal (nor behat) does that by default.
