### ISSUE TITLE
Support Lightning Media Upload on Fields

### ISSUE THREAD

**Issue by albertski** [acquia/lightning#120]
Do you guys have plans to have the same media uploader (Nice view of images, drag and drop option..) on the field level?

I'm looking at the Entity Browser module but it doesn't work with Media plus it has tons of issue (It's understandable since it is relatively new).  My plan is to try to fix the Entity Browser module and create and upload and view widget that mimics what is in the CKEditor Media Upload.

Any suggestions?

**Comment by phenaproxima** [comment]
Your plan is actually identical to our plan, which we have started working on :) I'd like to replace our home-grown widget with an Entity Browser implementation -- the most important thing, to me, is that the UX (reasonably speedy, optimistic, simple, attractive) and UI remain identical to what we already provide. Entity Browser's approach is completely different, but it offers more flexibility. So it'll take some doing, but we're working on exactly what you suggest.

**Comment by thejimbirch** [comment]
Thanks @phenaproxima!  That is great news.

**Comment by balsama** [comment]
In theory, this is now unblocked. A ticket on D.O would help get this into a future sprint.

**Comment by phenaproxima** [comment]
So here's the thing -- Lightning now provides an Entity Browser implementation out of the box. It is functionally identical to what we had before, and it still integrates with WYSIWYG, but because it is an entity browser, it can also integrate with fields. The browser that Lightning provides is only for use with entity reference fields that reference media entities, but it should be directly usable now -- just configure compatible fields to use that entity browser as their widget.

Thereofre, I'm not sure what else is needed in this issue; I'm not certain I'm in favor of having entity reference fields (at least, the ones that reference media entities) always use our browser by default, although that's certainly a possibility. It would help to have a little more direction on what, if anything, you'd like to see us add in this department...

**Comment by thejimbirch** [comment]
Thanks @phenaproxima  We are in the process of upgrading to RC7 and will review the Entity Browser you included.  I think this is exactly what we were looking for, the availability of an EB.  I don't think there is a need to dig into always using the browser by default.

**Comment by balsama** [comment]
We've implemented an image browser for new image fields (https://www.drupal.org/node/2767213). Currently discussing implementing the same for more general file fields. Let's open an issue on D.O to track that. Thanks!
