### ISSUE TITLE
Suggest moving scaffold dependency

### ISSUE THREAD

**Issue by GroovyCarrot** [acquia/lightning#142]
Is it possible to remove the dependency on `drupal-composer/scaffold` from this installation profile, and move it over to the project template (https://github.com/acquia/lightning-project)? It appears to be causing undesired behaviour when adding this install profile to an existing project, and seems like it belongs in the project template.

**Comment by phenaproxima** [comment]
Our development workflow requires the scaffold plugin in order for us to build Lightning instances quickly -- but as I think about this, I don't see any reason why it can't be moved into require-dev, rather than require. If you're willing submit a PR (and it passes our CI), I think I'd be in favor of that. :)

**Comment by GroovyCarrot** [comment]
Thanks for the quick feedback @phenaproxima, I've put a PR in and the build has passed. I imagine accepting it is subject to the require line adding to lightning-project?

**Comment by phenaproxima** [comment]
Lightning Project already requires the scaffold plugin, as it turns out, so it's just down a little bit of discussion with @balsama and some internal manual testing. Hopefully we can merge it today.

**Comment by phenaproxima** [comment]
I like it. Merged!
