### ISSUE TITLE
Path aliases are not replicated

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#170]

**Comment by phenaproxima** [comment]
I've implemented a really basic form of this in 3ff8b89eda8b025d349817bade5be88f731dd12d.

**Comment by balsama** [comment]
Under certain circumstances, aliases seem to get deleted and it reverts to system paths.

**Comment by phenaproxima** [comment]
Okay, here are the steps to reproduce the problem. Assuming you have started out in the Live workspace (fresh install):

1. Switch to Stage
2. Create a node with an alias
3. Publish Stage
4. Switch back to Live
5. Edit the node and change its alias
6. Switch back to Stage
7. Update from Live

The url_alias table will now be corrupted (node 5 is the Stage version, and node 6 is the one that was replicated to Live):

5	/node/5	/stage/a-page	en
6	/node/5	/stage/behold	en

There is no alias for node/6, so when you switch back to Live and attempt to access the live alias, you'll get a 404 because the alias is gone.
