### ISSUE TITLE
[Feature Request] Add Cog theme in profile

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/lightning#187]
Add [Cog theme](https://www.drupal.org/project/cog) in profile as its mostly being used in most of the projects

cc / @sarahjean @aellison 
// Naveen

**Comment by phenaproxima** [comment]
The decision was made nearly a year ago to not ship themes with Lightning. We're trying to keep it as un-opinionated as possible, especially with display stuff, because Lightning was always intended for use in the wider Drupal community. I'm open to including a theme if there's a *really* compelling reason to do so, but I'm not seeing one here.

@balsama, what do you think?

**Comment by aellison** [comment]
I agree with @phenaproxima that Cog should be left out of Lightning.  As a highly opinionated toolset, it's more aligned with the BLT project than the lightning project.

CC: @sarahjean @jenter @skippednote

**Comment by phenaproxima** [comment]
The consensus here seems to be that Lightning should not be making theme decisions, so let's leave Cog out of Lightning until a wide use case arises for it.
