### ISSUE TITLE
Authenticated role should be able to use administration theme

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#209]
In the course of building a demo, I've had to switch in and out of a couple of user accounts with varying degrees of privilege. I cannot begin to describe how jarring it is that in certain circumstances I can see the (relatively nice and clean) Seven theme, and in others I can only use the main theme, which, more likely than not, lacks administrative styling and therefore looks like a hideous, barely-usable mess.

Lightning should change this, IMHO, and in new installs (not upgrades), it should give all authenticated users permission to use the administrative theme. Obviously that will not give them permission to use administrative pages, but if they DO need to use administrative pages, they should all be using the same theme.

**Comment by phenaproxima** [comment]
@koleary, any thoughts?

**Comment by koleary** [comment]
I totally agree. I have never been a fan of restricting authors admin experience via the theme. It's a blunt instrument instead of a scalpel. In addition to the problems Adam listed it's also condescending and makes authors feel like second-class citizens, not to mention creating a disconnect when admins have to explain something while simultaneously 'translating' instructions about what the author should see from the admin theme to the front end theme.

**Comment by phenaproxima** [comment]
Issue migrated to drupal.org: https://www.drupal.org/node/2825932
