### ISSUE TITLE
Authoring experience - selecting nodes for page construction

### ISSUE THREAD

**Issue by mospeed** [acquia/lightning#253]
As an author it should be possible to pick nodes (content) already created in the system while creating the page. Is it possible now or on the roadmap.

**Comment by phenaproxima** [comment]
Can you give me a little more info about what you're trying to do?

**Comment by mospeed** [comment]
Sure,
What i want to be able to do is enable the author to construct a page through the panels interface. But instead of placing only blocks. I want to be able to choose nodes of different content types in various regions. And have the same capabilities of dragging, moving and removing such nodes from the regions as i can do with blocks today.
The nodes hence placed should be able to call their corresponding (applicable) templates to bring out the entire page UI.

**Comment by balsama** [comment]
Blocks are baked in to Panels and Drupal 8 in general. So you'll have to use a block regardless. But what you can do is create a custom block type with a single node reference field which renders the referenced entity. I've attached sample config.

[lightning_node_reference_block.tar.gz](https://github.com/acquia/lightning/files/676157/lightning_node_reference_block.tar.gz)

**Comment by mospeed** [comment]
Thanks for the response.
I had explored this option as well, but if I am not mistaken this implementation will make as many numbers of blocks as there are its placements. And that is exactly what I want to work around. If the nodes are already present in the system then there should be a mechanism to leverage the node itself instead of creating another container(block) to place the node on the page. 

Ideally, if blocks were to be used to place the node on a page it might be better to reuse the block to place different nodes on different places on a page and on multiple pages instead of making that many numbers of instances of blocks.

**Comment by balsama** [comment]
You are correct. There are some possible solutions to that. I'm going to put this issue into our next sprint to explore our options.

**Comment by NeelamChaudhary** [comment]
I am trying to find the solution for this with some approaches and can I have your recommendation on the approach taken so that I can decide on to extend the lightning distribution
or implement some other supporting modules.


Approach 1:- Rendering the node itself in any region without wrapping it into block.
Challenge ::- There seems some difficulty in combining node displays with blocks rendered e.g. moving the blocks and node rendered within the region itself.
              
Approach 2:- Using views to render content related to any node and passing the selected node as contextual filter to the views block.
With this approach the same views block can be placed in any region or in multiple regions on the same page and the templates and some settings can be different for each region.
Challenge::- Difficult to create standalone module very little modification needs to be done in panels_ipe module.
                                                
Approach 3:- Using block content to render the content of any node. The config form of any block can be exposed while placing the block in any region with panels_ipe.
Currently I am working on analyzing the feasibility of this approach and I am trying to expose block config form in panels_ipe form for placing any block.
Saving the page or region specific block config settings in panels config itself and rendering the content with the given settings so the content in the block can be rendered differently while only one block will be created at the back end.
Challenge::- Altering the block content dynamically based on the page and region seems challenging. Exposing all the block config variables to JS might cause some security issue.

The information for rendering the node or any content with any of the approaches will be stored with the panels config info and can be used at the time of rendering the page.

I have done some implementations with approach 1 and approach 2 stated above and I am currently working on approach 3.
I prefer approach 2 because power of views can be utilized with this approach but there is unnecessary addition of views when views is not required.
Any thoughts?

**Comment by balsama** [comment]
Take a look at our next release plan: [[META] Lightning 8.x-2.03](https://www.drupal.org/node/2836394). Specifically:

* [#2667896: Provide a block type that can display any entity without a context](https://www.drupal.org/node/2667896)
* [#2842170: Introduce concept of inline/one-off blocks](https://www.drupal.org/node/2842170)

I think those two issues will likely solve the problem you are facing and I don't want you to duplicate work.

**Comment by mospeed** [comment]
this seems in line with what i am trying to achieve. Will keep a look out on its release.

Thanks for all the help

**Comment by balsama** [comment]
We ended up bringing the Entity Block module into Lightning for this. Check out https://www.drupal.org/node/2667896 for more info.
