### ISSUE TITLE
Unable to use media library on media reference fields

### ISSUE THREAD

**Issue by leonk** [acquia/lightning#266]
When setting a media reference field, and using the entity browser.  I'm unable to select any entities from the "view" page.

Steps to replicate:
1) Install lightning_media_image and all it's dependencies
2) Add a entity reference field, select "Other" as the reference type, then select media.
3) Allow image media entities to be selected
4) In the entity form display, set the field to use the entity browser widget.
5) Edit or add an entity.  When you are on the "view" tab you are unable to select any entities.

I've had a look into what is going on, and it seems that the browser.js is not included on the page (from the lightning_media.module).
So I tried including it on the page.  This still didn't work, looks like a call the Drupal.behaviors isn't fired once the entity browser is loaded.

**Comment by balsama** [comment]
I don't think I follow entirely. Which entity browser are you selecting? (Image browser or media browser?) And what's the end goal?

If you're just uploading images, can you just use the image reference field instead? Lightning will automatically select the image browser Entity Browser in that case.

**Comment by leonk** [comment]
Okay so it works if I reference the image entity directly, and not the media entity.

My use case is I need to reference the media entity, as we have a few additional fields for information we need to capture on the image.
I'm using the image_browser, but have modified it to include an inline entity form upload.

**Comment by balsama** [comment]
Ok. That makes sense. We might have an existing issue that this could fall under. Stay tuned.

**Comment by phenaproxima** [comment]
@leonk: From a cursory reading of this issue, I think that you may be running into something we did intentionally.

The image_browser entity browser was intended to work with core image fields, which are just specialized versions of file fields. Meaning that they expect to be referencing a file entity directly. The image browser does some jiu-jitsu around this, so that you can select and create media entities, but when you actually complete the selection, it returns the underlying file entities to the field.

The aforementioned jiu-jitsu is configurable; if you edit the image_browser entity browser and look at the Upload widget, you'll see that there is a checkbox labeled "Return source file entity". This is checked by default. If you uncheck it, the image_browser will return the media entity rather than the file entity -- but this will instantly break the image browser break on any image field in which it is used.

I would instead suggest that you duplicate and modify the media_browser entity browser. It is configured to return media entities directly, and should therefore work with media reference fields.

**Comment by phenaproxima** [comment]
#288 addressed this. I will re-open a new version of that PR shortly.

**Comment by balsama** [comment]
#298 now.

**Comment by phenaproxima** [comment]
I hope this helps :)
