### ISSUE TITLE
PHP 7 Dependency w/ doctrine/inflector

### ISSUE THREAD

**Issue by mikemadison13** [acquia/lightning#411]
The recent 1.2 update for https://github.com/doctrine/inflector/tree/1.2.x now requires PHP 7. Recently, my builds started failing on a project because of lightning's ^1 requirement for the library.

```
  Problem 1
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
  Problem 2
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
    - doctrine/common v2.7.3 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[v1.2.0].
    - Installation request for doctrine/common v2.7.3 -> satisfiable by doctrine/common[v2.7.3].
```

This can be corrected by manually requiring doctrine/inflector 1.1.

**Comment by balsama** [comment]
Same thing happened to me. This happens if:

- You project commits it composer.lock file (which is recommended under most circumstances)
- You build your composer.lock file locally with a different php version that your CI server (probably 7 or 7.1 locally while your CI server uses 5.6)

The solution is to rebuild your lock file with php 5.6. If you have php 5.6 installed, doctrine/inflector will automatically constrain itself to v1.1.0 which doesn't require php 7.

Lightning doesn't actually have a direct dependency on doctrine/inflector. The tree with php <=7.1 looks like this:

```
acquia/lightning:2.1.7 requires:
drupal/core:~8.3.1, which currently will resolve to 8.3.5, which requires:
doctrine/common:^2.5, which will resolve to 2.8.0
```

If you have php 7.0 installed:

```
acquia/lightning:2.1.7 requires:
drupal/core:~8.3.1, which currently will resolve to 8.3.5, which requires:
doctrine/common:^2.5, doctrine/common:2.8.0 requires php ~7.1, so it will resolve to 2.7.3, which requires:
doctrine/inflector:1.*, which will resolve to doctrine/inflector:1.2.0
```

if you have php 5.6 installed:

```
acquia/lightning:2.1.7 requires:
drupal/core:~8.3.1, which currently will resolve to 8.3.5, which requires:
doctrine/common:^2.5, doctrine/common:2.8.0 requires php ~7.1, so it will resolve to 2.7.3, which requires:
doctrine/inflector:1.*, doctrine/inflector:1.2.0 requires php:^7.0, so it will resolve to 1.1.0 (which simply requires php:>=5.3.2, so no problem!)
```

**Again, tl;dr is generate your lock file in an environment running the same php version as your CI/prod environments.**

**Comment by balsama** [comment]
I turned this into a blog post: http://lightning.acquia.com/blog/acquia-doctrine-dependencies
