### ISSUE TITLE
Why does lightning depend on dblog, and can this dependency be removed?

### ISSUE THREAD

**Issue by aaronsenecal** [acquia/lightning#428]
Presently, it looks like Lightning lists the Database Logging (dblog) as a hard requirement (line 30 of lightning.info.yml), preventing users from disabling the module in favor of an alternative logging backend (like Syslog). 

Because of the database performance and storage risks imposed by the Database Logging requirement, would it be possible to soften this dependency so that users aren't forced to hack the profile in order to disable the module?

**Comment by balsama** [comment]
Lightning lists dblog in its dependencies array because it wants it installed, not because it depends on it. Nothing in Lightning assumes dblog is installed and nothing in Drupal prevents you from uninstalling a dependency of a profile (unlike dependencies of modules).

I'm pretty sure this works as designed, but let me know if you think I'm missing something.

**Comment by rickvug** [comment]
@balsama The fix here is to install the module programmatically in the lightning.install file rather than list dblog as a dependency in lightning.info.yml. The code to enable should be this (use statement missing):
`
\Drupal::service('module_installer')->install(['dblog']);
`

I did exactly this back in Drupal 7 for a distribution I was building. I'd actually go as far as to suggest that any modules that Lightning suggests but doesn't depend on should be installed in this manner to provide implementors greater flexibility.

**Comment by aaronsenecal** [comment]
Ooo, I like that idea, @rickvug. This would definitely help to avoid some of the confusion that site builders may encounter when checking interfaces like "/admin/modules" and `drush pmi` to see if dblog (and others of its ilk) can be disabled. 

Since both Database Logging and Syslog are included by default in Drupal core, I'm wondering if it'd make sense to add another pre-install step to Lightning's setup form that allows users to choose which logging module they'd like to use right out of the gate.

**Comment by rickvug** [comment]
@aaronsenecal I've talked to @balsama a bit more on chat. I think that both of us are confused. In D8 listing a module in the profile's requirements does not make it a hard requirement. Dblog just looks like a hard requirement because of how D8's module install/uninstall system works. You can no longer just disable a module, which is why it is greyed out. If you go over to the uninstall tab I can confirm that you indeed can uninstall dblog. @balsama is right on this.
