### ISSUE TITLE
Determine workflow for OAuth keys

### ISSUE THREAD

**Issue by balsama** [acquia/lightning#445]
Lightning API generates a pair of OAuth keys on install, saves them to a random directory inside the system temp dir, and then creates config to reference the new keys.

The problem is that the config that references the keys will be exported/imported in a normal workflow, but the keys the config references will not because they are outside of VCS root.

Possible solutions:
* Since we indicate that the keys are for development only, and should be changed before going into production, we could put the keys in a known location (like VCS root, one level up from docroot).
* Document implementing something like Config Split to exclude the keys config for all environments. Perhaps Lightning could actually configure that if Config Split is present?

**Comment by balsama** [comment]
@damontgomery Did you come across this issue with the Reservior + BLT POC you built? Any suggestions on how to best handle it?

**Comment by damontgomery** [comment]
There are two issues.

1. The tmp directory probably gets cleared regularly.
Solution: I store the keys in `/oath/private.key` if you want to commit them to the repo. Probably not the best long term solution, but OK for dev. Since it's probably not a good idea to spread the keys around, I recommend not creating keys for people.

2. The key directory needs to be absolute.
Solution: Store the keys in a relative directory and modify the OAuth module to use a relative path (I haven't tried this).

Solution: Don't export the OAuth configuration. Each site should be it's own client with it's own auth keys, so exporting doesn't make sense unless you use config split. Because the paths are absolute, also need different settings on local then on the server. One temporary solution (probably not a great long term solution either) is to upload the keys to the hosted server in a directory accessible to the web host that you can control permissions. You could add this to a deploy process like cloud hooks on Acquia hosting.

**Comment by balsama** [comment]
I think a good workaround for now is:

1. Stop generating keys on install
2. Provide an option to automatically generate keys somewhere in the UI
3. The key generation UI should ask for an absolute path in which to store them. We should recommend the /home directory, since it's persistent and reliable on Acquia Cloud)
4. The /home directory _may_ be shared by multiple environments, but that is not guaranteed. Considering this, we should continue to give the keys unique name so that there are no conflicts between environments.
5. The user will be responsible for excluding the config for they from export/import since it will be different on different environments (using Config Split or otherwise).

**Comment by balsama** [comment]
From @danepowell:

> One thing to be aware of for troubleshooting purposes: simple_oauth calls realpath on the key directory, which requires that PHP have execute permissions on every directory in the file path. This makes it somewhat brittle and can cause unexpected problems in some environments.

**Comment by balsama** [comment]
Fixed in: #454

**Comment by danepowell** [comment]
Just for posterity, here's how I implemented a solution for key management using config split:

1) Generate default "snakeoil" keys that will be used when environment-specific keys are not available. Place them at <repo-root>/keys/snakeoil_private.key and <repo-root>/keys/snakeoil_public.key
2) Modify your simple_oauth.settings to have the following keys:
    ```
    private_key: ../keys/snakeoil_private.key
    public_key: ../keys/snakeoil_public.key
    ```
    This will allow the site to install and use the snakeoil keys in all environments. Obviously these are insecure though, so in production environments (ACE) you'd want to use config split to override these:
3) Generate production keys on ACE at /home/mysite/env_private.key and /home/mysite/env_public.key
4) Create a config split of simple_oauth.settings.yml for these environments referencing these keys:
    ```
    private_key: /home/mysite/env_private.key
    public_key: /home/mysite/env_public.key
    ```

One thing to be aware of for troubleshooting purposes: simple_oauth calls realpath on the key directory, which requires that PHP have execute permissions on every directory in the file path. This makes it somewhat brittle and can cause unexpected problems in some environments.

**Comment by danepowell** [comment]
To add to the above: you _must_ generate server-side keys on ACE even for dev environments, because the snakeoil keys will be deployed with permissions that break site installs. Similarly, on local sites, you'll need to change the key permissions manually after initially checking out the codebase.
