### ISSUE TITLE
Remove lightning_scheduled_updates configuration from node.type.page

### ISSUE THREAD

**Issue by sylus** [acquia/lightning#448]
Hi there!

Since lightning_scheduled_updates is now completely opt in functionality, I was wondering if we could remove the following lines from node.type.page found in lightning_page. 

```sh
  lightning_scheduled_updates:
    embargo: true
```

Since I have opted out of lightning_scheduled_updates I was getting issues when editing my configuration revolving around node.type.page still calling scheduled_updates components.

```sh
langcode: en
status: true
third_party_settings:
  menu_ui:
    available_menus:
      - main
    parent: 'main:'
  workbench_moderation:
    enabled: true
    allowed_moderation_states:
      - archived
      - draft
      - needs_review
      - published
    default_moderation_state: draft
  lightning_scheduled_updates:
    embargo: true
name: 'Basic page'
type: page
description: 'Use <em>basic pages</em> for your static content, such as an ''About us'' page.'
help: ''
new_revision: true
preview_mode: 1
display_submitted: false

```

**Comment by phenaproxima** [comment]
If you're not going to be using Scheduled Updates, it should be completely safe to remove those lines from your own (live) config. But I don't think we can remove it from the config stuff that ships with LIghtning itself.

Why? Because those lines are how Lightning Scheduled Updates knows to attach itself to that node type in the first place, since it could be installed before or after the node type.

**Comment by sylus** [comment]
Ah that makes perfect sense and the solution was exactly what I did :)

Closing this issue and thanks for clarifying the correct approach!
