### ISSUE TITLE
Cannot Ship a lightning subprofile with multiple languages enabled.

### ISSUE THREAD

**Issue by pavlosdan** [acquia/lightning#483]
Could the patch in this Drupal Core issue be applied to the Lightning base profile to allow shipping a subprofile with multiple languages? As it stands right now, trying to install a subprofile with more than one language enabled fails.

https://www.drupal.org/node/2413191

**Comment by balsama** [comment]
Interesting. I wasn't aware of that issue.

To be clear, the sub-profile or your root composer.json file could supply the core patch, correct? While this is a totally valid use case and is a legit problem, I'd rather ask that you solve it in your sub-profile instead of bringing in another core patch to Lightning.
