### ISSUE TITLE
Missing DBUpdate & Errors 2.2.1

### ISSUE THREAD

**Issue by mwetmore** [acquia/lightning#498]
When following the update process, I'm missing one of the updates, anything I can check to make sure 8002 should be getting loaded?

The following updates are pending:

```
lightning_media module : 
  8018 -   Updates the media browser's argument validation. 

media_entity module : 
  8200 -   Clears the module handler's hook implementation cache. 
  8201 -   Replace Media Entity with Media. 
```
I believe I am missing:

```
lightning_api module : 
  8002 -   Installs the Consumers module.
```

This warning also shows when you kick off the update:

```
Warning: Invalid argument supplied for foreach() in _media_entity_get_incompatible_modules() (line 58 of modules/contrib/media_entity/media_entity.install).
_media_entity_get_incompatible_modules() (Line: 207)
media_entity_requirements('update')
call_user_func_array('media_entity_requirements', Array) (Line: 402)
Drupal\Core\Extension\ModuleHandler->invokeAll('requirements', Array) (Line: 98)
update_check_requirements() (Line: 154)
Drupal\system\Controller\DbUpdateController->handle('info', Object)
call_user_func_array(Array, Array) (Line: 110)
Drupal\Core\Update\UpdateKernel->handleRaw(Object) (Line: 73)
Drupal\Core\Update\UpdateKernel->handle(Object) (Line: 28)
```
This warning is also thrown:
```
Invalid argument supplied for foreach() media_entity.install:58                                                                   [warning]
In order to run the Media Entity 2.x upgrade, please uninstall and remove from the codebase the contributed "Media" module.
```

I've performed the update in place with the commands to update through composer, I also reset everything, wiped out my modules/core and received the same errors.

**Comment by balsama** [comment]
Hmmm. A couple of possibilities:

* It's possible that even after wiping our core and modules directory, you still might need to run composer update a couple of times. Especially to get the core patches.
* Did you clear caches *before* running your updates and *after* updating your code? It's possible that you did, but you also didn't have all of your code updated.

We've exposed a few requirements bugs in the update path today (after an upstream package *fixed* a bug!) and we might release another patch release in the coming days to address. (that shouldn't stop you from upgrading, but if you're having trouble, you might want to wait)

**Comment by mwetmore** [comment]
Hmmmm let me run through this one more time, I might hold off for a few days while the kinks get worked out...no major reason for us to upgrade yet.

**Comment by mwetmore** [comment]
Yeah, tried that a few times and it indicates that there is nothing to update.  I'm going to hold off for now, maybe try again in a couple of days.

Is there a way to verify that the patches have been pulled down?

**Comment by balsama** [comment]
> Is there a way to verify that the patches have been pulled down?

You could compare the output of composer update with /everything/ listed in the composer.json

**Comment by mwetmore** [comment]
If I try to proceed and do the updates that I do have available I get:
```
Performing media_entity_update_8200                                                                                               [ok]
The "generic" plugin does not exist.                                                                                              [error]
Performing media_entity_update_8201                                                                                               [ok]
Failed: The "generic" plugin does not exist.                                                                                      [error]
```
I can see patches getting applied through the `composer update` I can even see the update lightning_api_update_8002 but Drupal doesn't seem to see it.  I'm going to let it sit for now, kind of making my head spin.

**Comment by mwetmore** [comment]
Decided to come back to this again, these are the steps I'm performing:

1. blt sync:refresh to download a copy of our dev site.  drush cr just to clear things out.
2. Create a new branch for the update.
3. Delete composer.lock, docroot/core, docroot/modules/contrib
4. composer update
5. drush cr
6. drush updatedb 

I still only see 3 DB updates and not 4, when I proceed with the 3 only I get similar errors above related to "generic" plugin not being found.

Any ideas?

**Comment by phenaproxima** [comment]
Hi @mwetmore, do you have media_entity_generic installed? That may be the reason you're seeing this. https://www.drupal.org/project/media_entity_generic

**Comment by mwetmore** [comment]
@phenaproxima I haven't specifically added media_entity_generic, this is a fairly basic Lightning install...

**Comment by phenaproxima** [comment]
Lightning will not bring that module in because it won't be needed to complete the upgrade path in all cases. However, if it's complaining about that, try installing Media Entity Generic and running the update again (you may need to restore your database from a previous backup in order to run the update again). If it works, be sure to let me know...this will help us in the Media Initiative stabilize the upgrade path.

**Comment by mwetmore** [comment]
Thanks!  I'm going to give it a shot and see what happens.  I did check, I added a new Media Bundle and it's type provider is "Generic Media".  Any thoughts on the missing "Consumers" update?

**Comment by phenaproxima** [comment]
If you have a media bundle whose type provider is "Generic Media", that is almost certainly the reason that Media Entity is complaining about the lack of media_entity_generic.

In Media Entity 1.x, the generic type provider was included. In 2.x, it has been split out into the media_entity_generic module (which is compatible with core Media, which does not include a generic media plugin). Therefore, if Media Entity detects that you've used the generic type provider on any media bundles, it will complain until it sees media_entity_generic is in your code base. That is 100% expected, and poorly documented, behavior :)

Regarding the Consumers update -- well, Lightning did include an update hook, in lightning_api, which is supposed to install Consumers, *before* any media stuff happens since entity type definition rebuilds can inadvertently cause errors. It is possible that the lightning_api update has already run, and therefore the update dependency graph is not being resolved correctly.

My recommendation is just to manually enable Consumers before executing the updates, if you can. ```drush -y en consumers```. (Lightning's update hook does exactly that, just not using Drush.)

**Comment by mwetmore** [comment]
Sounds good, appreciate the detailed feedback, going to give this a shot and see how it goes!

**Comment by mwetmore** [comment]
I think the Media Entity Generic was the missing piece, I added that to the project first, and also enabled the Consumers module, then ran through the original steps and everything seems to be fine locally.  I'll have this fully tested on our dev site in a couple of days, so for now you can close this issue.  Thanks to both of you for all the assistance and guidance!
