### ISSUE TITLE
Unable to Fresh Install v2.2.2

### ISSUE THREAD

**Issue by CoolBlueNerd** [acquia/lightning#509]
Hello,

When trying to do a fresh install of the distro, it errors out after you enter in your database information with the following: 

`Configuration objects (sytem.theme) provided by system already exist in active configuration...`

Followed by a lot of other errors. At first I thought it was something to do with the just-recent released Drupal 8.4.1, as there's a patch for Drupal 8.4.1 that fails when doing a composer update. Essentially, I've found out that I can only use Acquia/Lightning v 2.2.1 with only Drupal/Core 8.4.0. Any other configuration of one of the latest versions (L 2.2.2 + C 8.4.1, or L 2.2.1 + C 8.4.1, or L 2.2.2 + C 8.4.0) does not work.

**Comment by WidgetsBurritos** [comment]
I'm seeing this same issue.

**Comment by scm6079** [comment]
Confirmed here as well, cannot perform an install of 2.2.2, running on Linux (CentOS 7).  Errors from the web interface and Drush.  Drush site:install error is essentially the same as @CoolBlueNerd stated:

`[error]  Configuration objects (system.theme) provided by system already exist in active configuration`

Installation fails with only the cache* tables and config table created, and only 4 entries in the config, the most recent being the "system.theme" entry, in my case set to `a:2:{s:7:"default";s:6:"stable";s:5:"_core";a:1:{s:19:"default_config_hash";s:43:"9Lf6qT5MMTVxvEoJiDGPpmoR3pPK7cBT93Y3ibVnTe4";}}`

**Comment by balsama** [comment]
This is because a core patch is no longer applying to 8.4.1. You can pin to drupal/core:8.4.0 for now. We'll have another new release (2.2.3) out in a bit with an update patch.

**Comment by garrowsmith** [comment]
@balsama unable to install site ```drush site-install``` using a minimal build with acquia/blt:8.9.10,  acquia/lightning:2.2.3, drupal/core:8.4.1 with a variation in config already exists error.

```Drupal\Core\Config\PreExistingConfigException: Configuration objects (core.entity_form_display.media.image.default, core.entity_view_display.media.image.default, media.type.image) provided by [error]
lightning_media_image already exist in active configuration in /var/www/sandbox/docroot/core/lib/Drupal/Core/Config/PreExistingConfigException.php:65```

**Comment by scm6079** [comment]
Locking it to Drupal/core 8.4.0 instead of 8.4.1 did not resolve the install error for us.  Although we make it significantly further in the install, it eventually fails during the installation step with:

`An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?rewrite=ok&profile=lightning&langcode=en&id=1&op=do_nojs&op=do
StatusText: OK
ResponseText: Drupal\Core\Config\PreExistingConfigException: Configuration objects (core.entity_form_display.media.image.default, core.entity_view_display.media.image.default, media.type.image) provided by lightning_media_image already exist in active configuration in Drupal\Core\Config\PreExistingConfigException::create() (line 65 of /web/Newsroom/WebSite/docroot/core/lib/Drupal/Core/Config/PreExistingConfigException.php).`

**Comment by balsama** [comment]
The patch was rerolled and brought into 2.2.3, which addresses the initial issue.

@scm6079 That error indicates that core isn't properly patched from [this issue](https://www.drupal.org/node/2883813). We include that patch with Lightning, but getting composer-patches to apply it properly might require running composer update more than once. See our release notes for more information.

**Comment by WidgetsBurritos** [comment]
I can confirm that Acquia Lightning 2.2.3 + Drupal 8.4.1 works. 👍 

Thanks for the quick action on this @balsama

**Comment by scm6079** [comment]
Confirmed here as well. IMO, this can be closed.

**Comment by simesy** [comment]
Word of warning to those coming here after googling errors. If you're including Lightning from a parent composer file, check you have `enable-patching: true` in your parent.
