### ISSUE TITLE
Patch pointing to diff file instead of patch file in Lightning 2.23

### ISSUE THREAD

**Issue by amytackett** [acquia/lightning#520]
composer.json contains this patch: "2880334 - Add update path of media_entity config changes from 1.x to core media module": "https://www.drupal.org/files/issues/media-entity-1.6--c564fc4.diff". The patch is referencing a .diff file. It needs to be referencing the .patch file instead.

**Comment by balsama** [comment]
Hi. Why should this be changed? Generally, we use the ".patch" extension when creating diffs. E.g.:

```
git diff > issue.patch
```

The extension is arbitrary. In this case, we created the file a few different ways because we had trouble getting such a huge patch to apply. That's why you see the different extensions in that issue.

**Comment by amytackett** [comment]
When I ran composer install, composer threw an error saying that it was unable to install that patch. I took a look at the files and saw that there was both a .diff and a .patch file and that their contents are different, so I thought perhaps that was the root cause. 

Perhaps, however, I had a different issue going on. I was upgrading a 2.1.8 site to 2.2.3. After I upgraded the code, I ran drush updb, and it erred out. I ended up destroying and rebuilding my vagrant machine, and then running into the composer error. 

It seems likely it is something else with my borked upgrade causing the problem. I am going to try starting over and upgrading to 2.2.0 and then incrementally through the dot releases to see if that will work.

**Comment by balsama** [comment]
That patch and composer-patches are both very finicky. There is a known issue with composer-patches and git 2.14. If you're using that you could try downgrading to 2.13.x.

The real solution is for the Media team to cut a release of the 2.x branch of the Media Entity module so that we don't need that huge patch anymore. Hopefully that happens before our next release.

Anyway, we're migrating all of our issues to D.O. I don't think this one needs to be migrated, but please reopen over there if you think it does.
Thanks!
