### ISSUE TITLE
Menu links are still visible to privileged users

### ISSUE THREAD

**Issue by phenaproxima** [acquia/lightning#93]
If you create a node in an unpublished state, and make a menu link to it, the menu link is visible to any user who has access to the node.

This is standard core behavior, but I can't shake the suspicion that it might be very confusing, and potentially alarming, to users. If the link shows up in the menu, they might think it's "published" -- because it has a link in the menu that looks like any other link. Or they might be perfectly clear that the content is unpublished, but the presence of the menu link, looking for all the world like any other, might lead them to think that their live site now has an invalid link in the menu.

I'm not sure if this is something Lightning should address; honestly, I'd like to see it tested with real users to determine if it's even a problem. But my instinct is to say that we should completely separate the concepts of content and menu links -- by removing the "Create a menu link" option from the node form.

**Comment by phenaproxima** [comment]
For the record, I ran this past @koleary and he thinks that this is something that should be tabled unless it turns out to be a real issue in usability testing. Do nothing? Can do!

**Comment by balsama** [comment]
While this is something that lightning _could_ improve on (if it was decided that a different behavior is indeed an improvement) - it would be better to change this in core.

Even if it were decided to change this behavior in core, I wouldn't want to introduce to lightning before then because it's a behavior that users expect and would probably lead to confusion. Closing as won't fix for now, but we can revisit if something changes.
